owner: infinitytx
repo: cbstatus

sites:
  - name: Infinity Wiki
    url: https://infinitythewiki.com/

  - name: Corvus Belli Forums
    url: https://forum.corvusbelli.com

  - name: Infinity ARMY
    url: https://infinityuniverse.com/army/infinity

  - name: Corvus Belli Online Store
    url: https://store.corvusbelli.com/en/

  - name: Infinity ARMY API
    url: https://api.corvusbelli.com/
    expectedStatusCodes:
      - 403

  - name: Infinity ARMY API (Army Metadata)
    url: https://api.corvusbelli.com/army/infinity/en/metadata
    headers:
      - "Origin: https://infinityuniverse.com"

  - name: CorvuSphere
    url: https://sphere.corvusbelli.com/

status-website:
  cname: cbstatus.infinitytx.org
  logoUrl: https://assets.corvusbelli.net/store/images/not-found.png
  theme: night
  name: CB Status
  introTitle: "**Corvus Belli Status**"
  introMessage: Monitoring the availability of Infinity-related websites. Transient outages of durations less than 5-10 minutes may not be detected.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Infinity Texas
      href: https://infinitytx.org
i18n:
  footer: Questions, comments, or suggestions? Visit our [Github Repo]($REPO)!
