owner: infinitytx
repo: cbstatus

sites:
  - name: Infinity Wiki
    url: https://infinitythewiki.com/
  - name: Corvus Belli Forums
    url: https://forum.corvusbelli.com
  - name: Infinity ARMY
    url: https://infinityuniverse.com/army/infinity

status-website:
  cname: cbstatus.infinitytx.org
  logoUrl: https://assets.corvusbelli.net/store/images/not-found.png
  theme: night
  name: CB Status
  introTitle: "**Corvus Belli Status**"
  introMessage: Are you wondering if the Wiki, Forums, or Army Builder are down? Here's what Github thinks.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Infinity Texas
      href: https://infinitytx.org
